In [1]:
pip install numpy --upgrade

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------------- -------------------------- 20.5/60.8 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.8 kB 325.1 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.8 kB 245.8 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.8 kB 262.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.8 kB 262.6 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 215.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 655.4 kB/s eta 0:00:20
   ---------------------------------------- 0.1/12.6 MB 853.3 kB/s eta 0:00:15
    --------------------------------------- 0.2/12.6 MB 952.6 kB/s eta 0:00:14
    ----

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.1.3 which is incompatible.
numba 0.59.1 requires numpy<1.27,>=1.22, but you have numpy 2.1.3 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.1.3 which is incompatible.
streamlit 1.32.0 requires numpy<2,>=1.19.3, but you have numpy 2.1.3 which is incompatible.


In [1]:
import numpy as np

In [2]:
array_a = np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
array_b = np.array([[1,2,3],[4,5,6]])

In [5]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.sqrt(array_b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [7]:
array_b[0]

array([1, 2, 3])

In [8]:
print(array_b[0][1])

2


In [9]:
print(array_b[0,1])

2


In [10]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array_b[0,1] = 5

In [12]:
array_b

array([[1, 5, 3],
       [4, 5, 6]])

In [13]:
array_b[:, 0] = 2

In [14]:
array_b

array([[2, 5, 3],
       [2, 5, 6]])

In [15]:
a = [1,2,4]

array_b[0] = a

In [16]:
array_b

array([[1, 2, 4],
       [2, 5, 6]])

In [17]:
array_b[:] = 9

In [18]:
array_b

array([[9, 9, 9],
       [9, 9, 9]])

In [19]:
ar_c = np.array([[1,2,3], [4,5,6]], dtype="float32")

In [20]:
ar_c

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [21]:
ar_d = np.array([[1,2,3], [4,5,6]], dtype= np.float32)

In [22]:
ar_d

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [23]:
ar_e = np.array([[1,2,3], [4,5,6]], dtype="str")

In [24]:
ar_e

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [25]:
ar_f = np.array([[1],[2]])

In [26]:
ar_g = np.array([1,2,3])

In [27]:
ar = np.add(ar_g, ar_d)

In [28]:
ar

array([[2., 4., 6.],
       [5., 7., 9.]])

In [29]:
ar = np.add(ar_f, ar_d, dtype = np.int32, casting='unsafe')

In [30]:
ar

array([[2, 3, 4],
       [6, 7, 8]], dtype=int32)

In [31]:
mean = np.mean(ar, axis=0)

In [32]:
mean

array([4., 5., 6.])

In [33]:
ar = np.array([[1,2,3], [4,5,6]])

In [34]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
br = ar[:1]

In [36]:
br

array([[1, 2, 3]])

In [37]:
cr = ar[1:]

In [38]:
cr

array([[4, 5, 6]])

In [39]:
ar = ar = np.array([[1,2,3,4,5,6], [4,5,6,6,7,8], [5,5,6,7,8,9]])

In [40]:
ar

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 6, 7, 8],
       [5, 5, 6, 7, 8, 9]])

In [41]:
ar[1, 1:]

array([5, 6, 6, 7, 8])

In [42]:
ar[:, 1:7:2]

array([[2, 4, 6],
       [5, 6, 8],
       [5, 7, 9]])

In [ ]:
initializing array

In [46]:
ar0 = np.zeros((2,2))

In [47]:
ar

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 6, 7, 8],
       [5, 5, 6, 7, 8, 9]])

In [48]:
ar0

array([[0., 0.],
       [0., 0.]])

In [49]:
ar1 = np.ones((2,2))

In [50]:
ar1

array([[1., 1.],
       [1., 1.]])

In [51]:
ar5 = np.full((2,2),5)

In [52]:
ar5

array([[5, 5],
       [5, 5]])

In [53]:
ar6 = np.full_like(ar5, 6)

In [54]:
ar6

array([[6, 6],
       [6, 6]])

In [55]:
ar7 = np.random.rand(2,3)

In [56]:
ar7

array([[0.95219712, 0.41180848, 0.05981395],
       [0.20250118, 0.545571  , 0.76957958]])

In [64]:
ar8 = np.random.randint(-5,8, size=(2,3), dtype=np.int64)

In [66]:
ar8

array([[ 6,  4,  4],
       [-2, -3,  1]])

In [67]:
ar1 = np.ones((5,5))

In [68]:
ar1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
ar0 = np.zeros((3,3))

In [70]:
ar0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
ar0[1,1] = 9

In [73]:
ar0

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [74]:
ar1[1:-1, 1:-1] = ar0

In [75]:
ar1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Mathematics 

In [76]:
a = np.array([1,2,3,4])

In [77]:
a + 2

array([3, 4, 5, 6])

In [78]:
a - 2

array([-1,  0,  1,  2])

In [79]:
a * 2

array([2, 4, 6, 8])

In [80]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [81]:
b = np.array([5,6,7,8])

In [82]:
a + b 

array([ 6,  8, 10, 12])

In [84]:
a = np.array([
    [1,2,3],
    [1,2,3]]
)

In [85]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [90]:
b = np.array([
    [4,5],
    [4,6],
    [4,5]
])

In [91]:
b

array([[4, 5],
       [4, 6],
       [4, 5]])

In [93]:
np.matmul(a,b)

array([[24, 32],
       [24, 32]])

In [94]:
np.dot(a,b)

array([[24, 32],
       [24, 32]])

In [95]:
a.dot(b)

array([[24, 32],
       [24, 32]])

### Reading txt file

In [5]:
import numpy as np
data = np.genfromtxt("data.txt", delimiter=",", dtype=np.int32)

In [6]:
data

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [10]:
data1 = np.loadtxt("data.txt", delimiter=',', dtype=np.int32)

In [11]:
data1

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [13]:
data1.reshape(1,54)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
        5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8,
        9, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [15]:
data1.reshape(2,27)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
        5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
        5, 6, 7, 8, 9]], dtype=int32)

### Concatenation of array

In [20]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])

In [22]:
c = np.concatenate((a,b), axis=0)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6], [1,2,3]])

In [26]:
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 1, 2, 3]])

In [27]:
c = np.concatenate((a,b), axis=0)
c

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [1, 2, 3]])

In [28]:
c = np.concatenate((a,b), axis=None)
c

array([1, 2, 3, 4, 5, 6, 4, 5, 6, 1, 2, 3])