## Beginner Level (1-10)
1.	Create and Inspect an Array
Create a 1D NumPy array of integers from 0 to 9 and print its shape, size, and data type.


In [4]:
import numpy as np

In [5]:
a = np.arange(10)
print(a)
print(a.shape)
print(a.size)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
(10,)
10
<class 'numpy.ndarray'>


#### Extract the even numbers from a 1D array of integers ranging from 1 to 20.

In [12]:
b = np.arange(1,21)
c =[b[b % 2 == 0]]
c

[array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])]

#### 3.	Array Reshaping
Reshape a 1D array of 12 elements (from 0 to 11) into a 3x4 2D array.


In [13]:
d = np.arange(0,12)
print(d)
d.reshape(3,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Create two 1D arrays of size 5 and perform element-wise addition, subtraction, multiplication, and division.

In [15]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a = a + 2
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
b = a - 3
b

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [20]:
c = a * 3
c

array([ 6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [21]:
d = a / 2
d

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

#### 5.	Array Indexing
Create a 2D array (3x3) and replace all elements in the second row with 7.


In [22]:
e = np.random.randint(1,10, size=(3,3))
e

array([[2, 9, 4],
       [2, 9, 3],
       [5, 8, 4]], dtype=int32)

In [23]:
e[1,0:3] = 7
e

array([[2, 9, 4],
       [7, 7, 7],
       [5, 8, 4]], dtype=int32)

#### 6.	Statistical Operations
Create a random array of 10 integers between 1 and 50. Find the mean, median, minimum, and maximum values.


In [33]:
f = np.random.randint(1,51,size=(3,4))
f

array([[37, 47, 21,  5],
       [24, 31, 22, 21],
       [36, 38, 21, 25]], dtype=int32)

In [34]:
print(f.mean())
print(np.median(f))
print(f.min())
print(f.max())


27.333333333333332
24.5
5
47


#### 7.	Boolean Masking
Create an array of integers from 0 to 10. Replace all elements greater than 5 with -1.


In [40]:
g = np.arange(0,10)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
g[g > 5] = -1
g

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

#### 8.	Matrix Multiplication
Create two 2x3 and 3x2 matrices and compute their dot product.


In [45]:
a = np.random.randint(1,51,size=(2,3))
b = np.random.randint(1,51,size=(3,2))
print(a)
print(b)

[[ 3 18  4]
 [32 42 35]]
[[16  5]
 [ 9 12]
 [15 39]]


In [46]:
c = a.dot(b)
c

array([[ 270,  387],
       [1415, 2029]], dtype=int32)

In [47]:
d = a@b
d

array([[ 270,  387],
       [1415, 2029]], dtype=int32)

In [49]:
e = np.matmul(a,b)
e

array([[ 270,  387],
       [1415, 2029]], dtype=int32)

#### 9.	Identity Matrix
Create a 4x4 identity matrix.


In [53]:
a = np.identity((4))
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 10.	Flatten an Array
Create a 3D array of shape (2, 3, 4). Flatten it into a 1D array.


In [54]:
a = np.random.randint(1,10,size=(2,3,4))
a

array([[[4, 9, 7, 9],
        [3, 8, 8, 8],
        [1, 6, 7, 9]],

       [[4, 4, 9, 5],
        [4, 1, 4, 6],
        [9, 2, 3, 8]]], dtype=int32)

In [57]:
a.reshape(-1)

array([4, 9, 7, 9, 3, 8, 8, 8, 1, 6, 7, 9, 4, 4, 9, 5, 4, 1, 4, 6, 9, 2,
       3, 8], dtype=int32)

In [58]:
a.flatten()

array([4, 9, 7, 9, 3, 8, 8, 8, 1, 6, 7, 9, 4, 4, 9, 5, 4, 1, 4, 6, 9, 2,
       3, 8], dtype=int32)

In [60]:
a.ravel()

array([4, 9, 7, 9, 3, 8, 8, 8, 1, 6, 7, 9, 4, 4, 9, 5, 4, 1, 4, 6, 9, 2,
       3, 8], dtype=int32)

#### 11.	Sorting
Create a 2D array of size 4x4 with random integers between 10 and 50. Sort it row-wise and column-wise.


In [62]:
b = np.random.randint(10,51,size=(4,4))
b

array([[10, 41, 40, 37],
       [38, 34, 46, 47],
       [26, 34, 35, 22],
       [45, 36, 41, 24]], dtype=int32)

In [66]:
print(np.sort(b,axis=0))
print(np.sort(b,axis=1))

[[10 34 35 22]
 [26 34 40 24]
 [38 36 41 37]
 [45 41 46 47]]
[[10 22 34 35]
 [24 26 34 40]
 [36 37 38 41]
 [41 45 46 47]]


#### 12.	Unique Elements
Generate a random array of size 15. Find all the unique elements and their counts.


In [73]:
a = np.random.randint(1,5,size=(15))
a

array([2, 3, 2, 1, 3, 4, 1, 4, 3, 1, 4, 3, 4, 1, 4], dtype=int32)

In [75]:
np.unique(a, return_counts=True)

(array([1, 2, 3, 4], dtype=int32), array([4, 2, 4, 5]))

#### 13.	File Reading (CSV)
Download and read a CSV file like data.csv. Use NumPy to calculate the sum of a specific column.
Example dataset: Iris Dataset.


In [82]:
a = np.genfromtxt("a.txt",delimiter=",")
a

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [4.3, 3. , 1.1, 0.1, nan],
       [5.8, 4. , 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, 0.3, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, 3.4, 1.7, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , 0.2, nan],
       [5.1, 3.3, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, 0.2, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3

In [78]:
a[:,0].sum()

np.float64(876.5)

In [79]:
a[:,1].sum()

np.float64(458.1)

In [80]:
a[:,2].sum()

np.float64(563.8)

In [81]:
a[:,3].sum()

np.float64(179.8)

In [85]:
b = np.genfromtxt("b.txt",delimiter=",")
b

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [nan, 3. , 1.1, 0.1, nan],
       [5.8, nan, 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, 0.3, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, nan, 1.7, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , 0.2, nan],
       [5.1, 3.3, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, 0.2, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3

In [87]:
np.nansum(b[:,0])

np.float64(872.1999999999999)

#### 14.	Broadcasting
Create two arrays: one of size (3, 1) and another of size (1, 4). Use broadcasting to add them.


In [2]:
import numpy as np
a = np.random.randint(1,11,size=(3,1))
b = np.random.randint(1,11,size=(1,4))
print(a)
print(b)

[[10]
 [ 5]
 [10]]
[[4 3 2 9]]


In [3]:
c = a + b
c

array([[14, 13, 12, 19],
       [ 9,  8,  7, 14],
       [14, 13, 12, 19]], dtype=int32)

In [4]:
d = b + a
d

array([[14, 13, 12, 19],
       [ 9,  8,  7, 14],
       [14, 13, 12, 19]], dtype=int32)

#### 15.	Clipping Values
Create a random array of size 10 and clip its values to the range [3, 7].


In [17]:
e = np.random.randint(0,11,size=10)
e

array([ 7, 10,  1, 10, 10,  8,  3,  5,  7,  5], dtype=int32)

In [18]:
d = np.clip(e,3,7)
d

array([7, 7, 3, 7, 7, 7, 3, 5, 7, 5], dtype=int32)

#### 16.	Find Unique Elements
Create a 1D array with duplicate elements. Use NumPy to find and display the unique elements in the array, as well as their counts.


In [20]:
f = np.random.randint(20,35,size=50)
f

array([25, 24, 25, 30, 22, 26, 20, 26, 30, 34, 20, 32, 32, 26, 28, 21, 23,
       31, 20, 29, 29, 20, 23, 29, 34, 31, 30, 22, 20, 20, 21, 20, 30, 31,
       34, 29, 32, 26, 25, 21, 24, 33, 27, 32, 26, 29, 30, 34, 28, 27],
      dtype=int32)

In [25]:
g = np.unique(f,return_counts=True)
g[1].max()

np.int64(7)

#### 17.	Sorting and Indices
Generate a random 1D array of 15 numbers. Sort the array in ascending order and also retrieve the indices of the sorted array.


In [26]:
h = np.random.randint(10,35,size=15)
h

array([11, 10, 17, 23, 14, 25, 15, 15, 20, 19, 24, 22, 32, 23, 16],
      dtype=int32)

In [27]:
i = np.sort(h)
i


array([10, 11, 14, 15, 15, 16, 17, 19, 20, 22, 23, 23, 24, 25, 32],
      dtype=int32)

In [29]:
j = np.argsort(h)
j

array([ 1,  0,  4,  6,  7, 14,  2,  9,  8, 11, 13,  3, 10,  5, 12])

#### 18.	Broadcasting Operations
Create a 3x3 matrix and a 1D array of size 3. Perform a broadcasting operation to add the 1D array to each row of the matrix.


In [30]:
a = np.random.randint(50,100,size=(3,3))
a

array([[60, 65, 71],
       [66, 62, 84],
       [76, 72, 54]], dtype=int32)

In [31]:
b = np.random.randint(20,65,size=3)
b

array([41, 29, 27], dtype=int32)

In [32]:
a+b

array([[101,  94,  98],
       [107,  91, 111],
       [117, 101,  81]], dtype=int32)

In [33]:
b+a

array([[101,  94,  98],
       [107,  91, 111],
       [117, 101,  81]], dtype=int32)

#### 19.	Stacking Arrays
Generate two random 2D arrays of shape 3x3. Concatenate them both horizontally and vertically using NumPy stacking functions.


In [38]:
a = np.random.uniform(1,100,size=(3,3))
a

array([[82.76087522, 58.86388017, 98.09342607],
       [74.66830836, 38.04578583, 41.63001514],
       [14.04180434,  2.37717517, 28.7596291 ]])

In [43]:
b = np.random.uniform(1,100,size=(3,3))
b

array([[59.38637922, 49.86752824, 58.52035266],
       [34.51209065, 59.10175869, 27.49754061],
       [69.71312115, 95.74612156, 65.27769409]])

In [41]:
c = np.concatenate((a,b))
c

array([[82.76087522, 58.86388017, 98.09342607],
       [74.66830836, 38.04578583, 41.63001514],
       [14.04180434,  2.37717517, 28.7596291 ],
       [61.63927183, 65.51872833, 14.78737656],
       [ 9.54721126, 92.78232233, 57.91084628],
       [19.88301091, 93.30833178, 29.80804266]])

In [42]:
d = np.concatenate((a,b), axis=1)
d

array([[82.76087522, 58.86388017, 98.09342607, 61.63927183, 65.51872833,
        14.78737656],
       [74.66830836, 38.04578583, 41.63001514,  9.54721126, 92.78232233,
        57.91084628],
       [14.04180434,  2.37717517, 28.7596291 , 19.88301091, 93.30833178,
        29.80804266]])

In [44]:
np.vstack((a,b))

array([[82.76087522, 58.86388017, 98.09342607],
       [74.66830836, 38.04578583, 41.63001514],
       [14.04180434,  2.37717517, 28.7596291 ],
       [59.38637922, 49.86752824, 58.52035266],
       [34.51209065, 59.10175869, 27.49754061],
       [69.71312115, 95.74612156, 65.27769409]])

In [45]:
np.hstack((a,b))

array([[82.76087522, 58.86388017, 98.09342607, 59.38637922, 49.86752824,
        58.52035266],
       [74.66830836, 38.04578583, 41.63001514, 34.51209065, 59.10175869,
        27.49754061],
       [14.04180434,  2.37717517, 28.7596291 , 69.71312115, 95.74612156,
        65.27769409]])